---
- hosts: trusty
  gather_facts: no
  become: yes
  tasks:
  - name: Copy your flask app file to the Vagrant servers
    copy:
      src: /$PWD/app.py
      dest: /home/vagrant/app.py
  - name: installing pip3
    apt:
      name: python3-pip
      state: latest
  - name: install requirements module py
    pip:
      requirements: /vagrant/requirements.txt
      executable: pip3

  - name: run flask app
    shell: |
      nohup python3 app.py > log.txt 2>&1 &
